//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyOptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dexterity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dexterity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyOptions.Dexterity", typeof(Dexterity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local integer l_adjust, h_pos, v_pos, h_size, v_size;
        ///
        ///default form to &apos;Switch Company&apos;;
        ///default window to &apos;Switch Company&apos;;
        ///
        ///l_adjust = 230;
        ///
        ///Field_GetPosition(&apos;(L) Company Names&apos;, h_pos, v_pos);
        ///Field_GetSize(&apos;(L) Company Names&apos;, h_size, v_size);
        ///
        ///move field &apos;(L) Company Names&apos; to h_pos - l_adjust, -1;
        ///resize field &apos;(L) Company Names&apos; to h_size + l_adjust, -1;
        ///
        ///move field &apos;(L) RememberMe&apos; to h_pos - l_adjust, -1;
        ///resize field &apos;(L) RememberMe&apos; to h_size + l_adjust, -1;
        ///
        ///move field &apos;(L) SQL  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompanySwitchScript {
            get {
                return ResourceManager.GetString("CompanySwitchScript", resourceCulture);
            }
        }
    }
}
